# Generated by Django 5.0.4 on 2024-04-14 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CarBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('total_number', models.IntegerField(default=0)),
                ('buy_now', models.IntegerField(default=0)),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CarorSpareparts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('price', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=32)),
                ('year', models.IntegerField(default=2000)),
                ('mileage', models.IntegerField(default=0)),
                ('body_color', models.CharField(max_length=20)),
                ('interior_color', models.CharField(max_length=20)),
                ('engine', models.CharField(max_length=40)),
                ('transmission', models.CharField(max_length=40)),
                ('place', models.CharField(default='Bishkek', max_length=32)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='money.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='money.model')),
            ],
        ),
    ]
